SaudiArabiaGuide/SaudiArabiaGuide/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('main.urls'))
]

SaudiArabiaGuide/main/urls.py
from django.urls import path
from.import views 

app_name='main'

urlpatterns = [
    path('',views.home_page,name="home_page"),
    path('Distance/',views.distance_page,name="distance_page"),
    path('Currency/',views.currency_exchange,name="currency_exchange"),
    path('Weather/',views.weather_informations,name="weather_informations"),
    path('Riyadh/',views.riyadh_page,name="riyadh_page"),
    path('Jeddah/',views.jeddah_page,name="jeddah_page"),
    path('Al-ula/',views.alula_page,name="alula_page"),
    path('Abha/',views.abha_page,name="abha_page"),
    path("mode/light/",views.light_mode_view,name="light_mode_view"),
    path("mode/dark/",views.dark_mode_view,name="dark_mode_view"),
]

SaudiArabiaGuide/main/models.py
from django.db import models

# Create your models here.

SaudiArabiaGuide/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest,HttpResponse

from .helpers import distanceKm


# Create your views here.

def home_page(request:HttpRequest):
    return render(request,'main/home_page.html')


def distance_page(request:HttpRequest):
    distance = None
    
    if request.method == "POST":
        fromCity = request.POST["fromCity"]
        toCity = request.POST["toCity"]
        distance = distanceKm(fromCity, toCity)
        if distance is not None:
            distance = round(distance,2)
            
    print(distance) 
    return render(request,'main/distance.html', {"distance" : distance})

def currency_exchange(request:HttpRequest):
    return render(request,'main/currency.html')

def weather_informations(request:HttpRequest):
    return render(request,'main/weather.html')

def riyadh_page(request:HttpRequest):
    return render(request,'main/Riyadh.html')

def jeddah_page(request:HttpRequest):
    return render(request,'main/Jeddah.html')

def alula_page(request:HttpRequest):
    return render(request,'main/Al-ula.html')

def abha_page(request:HttpRequest):
    return render (request, 'main/Abha.html')


def dark_mode_view(requset: HttpRequest):

    response = redirect("main:home_page")
    response.set_cookie("mode", "dark")

    return response


def light_mode_view(requset: HttpRequest):

    response = redirect("main:home_page")
    response.set_cookie("mode", "light")

    return response

SaudiArabiaGuide/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.6.4.slim.min.js" integrity="sha384-GLhlTQ8iKt18Z8lH6ZNtu6e3//N9ZrL2U5CrmflUvoHX" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-b4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyjsHT5G+8pPqIwePPF64Fb6f4jW9HqFz6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style\base.css' %}">
    <title>{% block title %}{% endblock  %}</title>
    <style>{% block style %} {% endblock  %}</style>

</head>

<!--nav-->
    <body class="mt-3{%if request.COOKIES.mode == "dark" %} dark  {% endif %}" >
      <ul class="nav">
          <li class="nav-item">
              <a class="nav-link active " aria-current="page" href="{% url "main:home_page" %}">Home</a>
          </li>
          <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle dropdown-toggle-no-arrow" href="#" id="applicationsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Applications</a>
              <div class="dropdown-menu" aria-labelledby="applicationsDropdown" {% if request.COOKIES.mode == "dark" %} style="background-color:black; {% endif %}>
                  <h6 class="dropdown-header">Food delivery</h6>
                  <a class="dropdown-item" href="https://apps.apple.com/sa/app/hungerstation/id596011949" target="_blank">Hungerstation</a>
                  <a class="dropdown-item" href="https://apps.apple.com/us/app/toyou-delivery-more/id1196302015" target="_blank">ToYou</a>
                  <a class="dropdown-item" href="https://apps.apple.com/sa/app/jahez/id1137352156" target="_blank">Jahez </a>

                  <h6 class="dropdown-header">Transportation</h6>
                  <a class="dropdown-item" href="https://apps.apple.com/us/app/careem-rides-food-more/id592978487" target="_blank">Careem</a>
                  <a class="dropdown-item" href="https://apps.apple.com/us/app/uber-request-a-ride/id368677368?uclick_id=c33a8d2c-1390-4ad3-9c63-bb9b1997e716" target="_blank">Uber</a>
              </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle dropdown-toggle-no-arrow" href="#" id="ispDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Internet Service Providers</a>
              <div class="dropdown-menu" aria-labelledby="ispDropdown" {% if request.COOKIES.mode == "dark" %} style="background-color:black; {% endif %}>
                  
                  <a class="dropdown-item" href="https://www.stc.com.sa/content/stc/sa/en/personal/home.html" target="_blank">STC</a>
                  <a class="dropdown-item" href="https://www.mobily.com.sa/wps/portal/web/personal"target="_blank">Mobily</a>
                  <a class="dropdown-item" href="https://sa.zain.com/en"target="_blank">Zain</a>

              </div>
          </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle dropdown-toggle-no-arrow" href="#" id="emergencyNumbersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Emergency Numbers</a>
              <div class="dropdown-menu " aria-labelledby="emergencyNumbersDropdown" {% if request.COOKIES.mode == "dark" %} style="background-color:black; {% endif %}">
                  <!-- Dropdown titles -->
                  <h6 class="dropdown-header">Police</h6>
                  <a class="dropdown-item" href="Tel:999">999</a>
                  <h6 class="dropdown-header">Ambulance</h6>
                  <a class="dropdown-item" href="tel:997">997</a>
                  <h6 class="dropdown-header">Civil Defense</h6>
                  <a class="dropdown-item" href="tel:998">998</a>
                </div>
            </li>
            <div class="mode-icons">
                <a class="active text-black" aria-current="page" href= "{% url 'main:dark_mode_view' %}"><span class="material-symbols-outlined">mode_night</span></a>
                <a class="active text-black" aria-current="page" href="{% url 'main:light_mode_view' %}"><span class="material-symbols-outlined">light_mode</span></a>
            </div> 
        </ul>
  </body>
    
<!--content-->
  {% block content %}{% endblock %}
  
</body>

<!--footer-->
<footer class="footer_area section_padding_130_0">
      <div class="container">
        <div class="row">
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg-4">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Footer Logo-->
              <div class="footer-logo mb-3"></div>
              <!-- Copywrite Text-->
              <div class="copywrite-text mb-5">
                <p class="mb-0">Made <i class="lni-heart mr-1"></i>by<a class="ml-1" href=""> Shekha Aldossary</a></p>
              </div>
              <!-- Footer Social Area-->
              <div class="footer_social_area"><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest"><i class="fa fa-pinterest"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype"><i class="fa fa-skype"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></div>
            </div>
          </div>
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Widget Title-->
              <h5 class="widget-title">About</h5>
              <!-- Footer Menu-->
              <div class="footer_menu">
                <ul>
                  <li><a href="#">About Us</a></li>
                  <li><a href="#">Home</a></li>
                  <li><a href="#">News</a></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Widget Title-->
              <h5 class="widget-title">Tourism Related Links</h5>
              <!-- Footer Menu-->
              <div class="footer_menu">
                <ul>
                  <li><a href="https://www.visitsaudi.com/en?_ga=2.195965740.1252428729.1710371932-801729441.1708251668" target="_blank">Visit Saudi</a></li>
                  <li><a href="https://mt.gov.sa/" target="_blank">Ministry of Tourism</a></li>
                  <li><a href="https://www.tdf.gov.sa/content/TDF/TDF/en/Home.html" target="_blank">Tourism Development Fund</a></li>
                  <li><a href="https://redsea.gov.sa/" target ="_blank">Saudi Red Sea Authority</a></li>
                  <li><a href="https://www.acp.gov.sa/" target="_blank">Air Connectivity Program</a></li>
                </ul>
              </div>
            </div>
          </div>
          <!-- Single Widget-->
          <div class="col-12 col-sm-6 col-lg">
            <div class="single-footer-widget section_padding_0_130">
              <!-- Widget Title-->
              <h5 class="widget-title">Contact</h5>
              <!-- Footer Menu-->
              <div class="footer_menu">
                <ul>
                  <li><a href="#">Call Centre</a></li>
                  <li><a href="#">Email Us</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
</html>

SaudiArabiaGuide/main/templates/main/currency.html
{% extends "main/base.html" %}

{% block title %} Currency Exchange {% endblock  %}

{% block style %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<style>

    body{
        Background-color: white;
    }

    body{
        background-image: url('/static/images/sa-p1.webp') ;
        object-fit: cover;
    }
    .contact-form{
        background-color: rgba(240, 248, 255, 0);
        margin-top: 10%;
        margin-bottom: 5%;
        width: 60%;
    }
    .contact-form .form-control{
        border-radius:1rem;
    }

    .contact-form form{
        padding: 14%;
    }
    .contact-form form .row{
        margin-bottom: -7%;
    }
    .contact-form h3{
        margin-bottom: 8%;
        margin-top: -10%;
        text-align: center;
        color: #0062cc;
    }
    .contact-form .btnContact {
        width: 50%;
        border: none;
        border-radius: 1rem;
        padding: 1.5%;
        background: #dc3545;
        font-weight: 600;
        color: #fff;
        cursor: pointer;
    }
    .btnContactSubmit
    {
        width: 50%;
        border-radius: 1rem;
        padding: 1.5%;
        color: #fff;
        background-color: #0062cc;
        border: none;
        cursor: pointer;
    }

    .form-group{
        color:white;
    }
    
    .contact-form h3{
        color:white;
    }
</style>

{% endblock  %}


{% comment %} content {% endcomment %}
{% block content %}

<div class="container contact-form">
           
            <form method="post">
                <h3>Currency Exchange</h3>
               <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <p>Enter the amount you want to exchange with its currency (e.g., 20 USD):</p>
                            <input type="text" name="txtName" class="form-control" placeholder="" value="" />
                        </div>
                        <div class="form-group">
                            <p>Enter Tagret Currency (e.g., SAR):</p>
                            <input type="text" name="txtEmail" class="form-control" placeholder="" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Calculate" />
                        </div>
                    </div>
                </div>
            </form>
</div>



{% endblock  %}

SaudiArabiaGuide/main/templates/main/distance.html
{% extends "main/base.html" %}

{% block title %} <title>Distance Calculation</title>{% endblock  %}

{% block style %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    body{
        Background-color: white;
    }

    body{
        background-image: url('/static/images/sa-p1.webp') ;
        object-fit: cover;
    }
    .contact-form{
        background-color: rgba(240, 248, 255, 0);
        margin-top: 10%;
        margin-bottom: 5%;
        width: 60%;
    }
    .contact-form .form-control{
        border-radius:1rem;
    }
   
    .contact-form form{
        padding: 14%;
    }
    .contact-form form .row{
        margin-bottom: -7%;
    }
    .contact-form h3{
        margin-bottom: 8%;
        margin-top: -10%;
        text-align: center;
        color: #0062cc;
    }
    .contact-form .btnContact {
        width: 50%;
        border: none;
        border-radius: 1rem;
        padding: 1.5%;
        background: #dc3545;
        font-weight: 600;
        color: white;
        cursor: pointer;
    }
    .btnContactSubmit
    {
        width: 50%;
        border-radius: 1rem;
        padding: 1.5%;
        color: #fff;
        background-color: #0062cc;
        border: none;
        cursor: pointer;
    }

    .form-group{
        color:white;
    }
    
    .contact-form h3{
        color:white;
    }


    .result{
        display:flex;
        background-color:rgba(0, 0, 0, 0.737);
        border-radius:10px;
        width:500px;
        height: 40px;
        justify-content:center; 
        margin-left:90px;
    }

    .distance h2{
        color:white;
        font-family:'Times New Roman', Times, serif;
    }




{% endblock  %}


{% comment %} content {% endcomment %}
{% block content %}


<div class="container contact-form">
            <form method="post" action="{% url 'main:distance_page' %}">
                {% csrf_token %}
                <h3>Distance Calculation </h3>
               <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <p>Enter From City:</p>
                            <input type="text" name="fromCity" class="form-control" placeholder="From City" value="" />
                        </div>
                        <div class="form-group">
                            <p>Enter Distenation City:</p>
                            <input type="text" name="toCity" class="form-control" placeholder="To City" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Calculate" />
                        </div>
                    </div>
                </div>
               </form>
            <div class="result">
            {% if distance %}
               <span class="distance"><h2> The distance is: <span class="red">{{distance}} KM</span></h2></span>
            {% endif %}
            </div>
</div>
{% endblock  %}

SaudiArabiaGuide/main/templates/main/home_page.html
{% extends "main/base.html" %}
{% load static %}
{% block title %} Saudi Arabia Guide {% endblock  %}
{% block style %}
 <link rel="stylesheet" href="{% static "style/home_page.css" %}">
 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans|Varela+Round">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 
  img{
    width: 100%;
    height: 400px;
}

.masthead {
    height: 85vh;
    min-height: 300px;
    background-image: url('/static/images/sa-p1.webp') ;
    background-size: cover;
    object-fit:cover ;
    background-position: center;
    background-repeat: no-repeat;
    shadow : ;

  }

  

.services{
    display: flex;
    justify-content: space-between;
    margin-left: 200px;
    margin-right: 200px;
    column-gap: s;
    padding-top: 50px;
  }

.services a{
    text-decoration: none;
    color: aliceblue;
    font-size: 15px;
  }

  .container h3{
    font-family:'Times New Roman', Times, serif;
    font-size: xx-large;
}

.container p {
    font-size: large;
    margin-bottom: 10%;
    margin-top: 10%;
}


  body{
    background-color: rgb(220, 220, 220); 
    margin: 0;
    font-family: 'Muli', sans-serif;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    overflow-x: hidden;
  }

  
  .carousel {
    width: 100%;
    overflow-x: scroll;
    padding: 30px 0;
    position: relative;
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    
  }
  
  .carousel__container {
    white-space: nowrap;
    display: flex;
    justify-content: center;
    width:100%;
    background-color:#edf0f0; 
    border-radius:20px;
    padding-bottom:50px;
  }
  
  .categories__title {
   color: rgb(77, 55, 102);
    font-size: 28px;
    position: absolute;
    padding-left: 30px;
  }
  
  .carousel-item {
    width: 200px;
    height: 250px;
    border-radius: 20px;
    background-color: #95bcd6;
    overflow: hidden;
    margin-right: 10px;
    margin-top: 70px;
    display: inline-block;
    cursor: pointer;
    -webkit-transition: 1000ms all;
    transition: 1000ms all;
    -webkit-transform-origin: center left;
    transform-origin: center left;
    position: relative;
  }
  
  .carousel-item:hover ~ .carousel-item {
    -webkit-transform: translate3d(100px, 0, 0);
    transform: translate3d(100px, 0, 0);
  }
  
  .carousel__container:hover .carousel-item {
    opacity: 0.3;
  }
  
  .carousel__container:hover .carousel-item:hover {
    -webkit-transform: scale(1.5);
    transform: scale(1.5);
    opacity: 1;
  }
  
  .carousel-item__img {
    width: 200px;
    height: 250px;
    -o-object-fit: cover;
    object-fit: cover;
  }
  
  .carousel-item__details {
    background: -webkit-gradient(
      linear,
      left bottom,
      left top,
      from(rgba(0, 0, 0, 0.9)),
      to(rgba(0, 0, 0, 0))
    );

    background: linear-gradient(
      to top,
      rgba(0, 0, 0, 0.9) 0%,
      rgba(0, 0, 0, 0) 100%
    );
    font-size: 10px;
    opacity: 0;
    -webkit-transition: 450ms opacity;
    transition: 450ms opacity;
    padding: 10px;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
  }
  
  .carousel-item__details:hover {
    opacity: 1;
  }
  
  .carousel-item__details span {
    /* width: 10px;
    height: 10px; */
    font-size: 0.9rem;
    color: #2ecc71;
    /* background-color: white; */
  }
  
  .carousel-item__details .controls {
    padding-top: 180px;
  }
  

  {% comment %} العناوين ع الكاردز  {% endcomment %}
  .carousel-item__details .carousel-item__details--title,
  .carousel-item__details--subtitle {
    color: #fff;
    font-family:'Times New Roman', Times, serif;
    text-shadow: 2px 2px 8px black;
    margin: 5px 0;
    font-size: 20px;
  }    
  

.categories__title{
font-family:'Times New Roman', Times, serif;
font-size:xx-large;
color:black;
text-shadow: 2px 2px 8px #8cb6ba;
}

.dark .carousel__container{
background-color :#b5baba;
}


 
 {% endblock  %}


{% block content %}
<section class="m-0">
<header class="masthead">
  <div class="container h-100 mt-3">
    <div class="row h-100 align-items-center ">
      <div class="col-12 text-center">
        <h1 class="fw-light text-white mb-0">Saudi Arabia Guide</h1>
        <p class="lead text-white mt-2">We're Here to Make Your Journey Easer!</p>
        <div class="services">
          <a href="{% url "main:distance_page" %}">Distance Calculation </a>
          <a href="{% url "main:currency_exchange" %}"> Currency Exchange</a>
          <a href="{% url "main:weather_informations" %}">Weather Informations</a>
        </div>
      </div>
    </div>
  </div>
</header>
</section>
<!-- second section-->
<div class="container">
  <div class="row mt-5 "> 
    <div class="col-4">
      <div class="d-flex flex-column gap-3 h-100 justify-content-center">
        <h3> A Journey Through Timeless Heritage and Modern Wonders.</h3>
      </div>
    </div>
    <div class="col order-1 order-md-2">
      <p>Embark on a journey to the heart of Arabia, where ancient heritage intertwines with modern marvels. 
        Saudi Arabia, a realm of vibrant contrasts, invites you to explore its boundless beauty—from the rhythmic beats 
        of traditional music to the tantalizing aroma of authentic cuisine. Discover the warmth of hospitality, the allure
        of untouched landscapes, and a captivating blend of the old and the new. Join us on an odyssey where history and 
        future entwine, unveiling the magic of Saudi Arabia—an extraordinary place waiting to be explored.
      </p>
    </div>
  </div>
</div>



<!-- third section-->

    <section class="carousel overflow-hidden">
      <h2 class="categories__title">Destinations in Saudi Arabia</h2> 
      <a href="{% url "main:riyadh_page" %}"><div class="carousel__container">
        <div class="carousel-item">
          <img
            class="carousel-item__img"
            src="{% static "images/Riyadh.jpg" %}"
            alt="people"
          />
          <div class="carousel-item__details">
            <h5 class="carousel-item__details--title">Riyadh</h5>
          </div>
        </div></a>
        <a href="{% url "main:alula_page" %}"><div class="carousel-item">
          <img
            class="carousel-item__img"
            src=" {% static "images/Al-ula.jpg" %} "
            alt="people"
          />
          <div class="carousel-item__details">
            <h5 class="carousel-item__details--title">Al-ula</h5>
          </div>
        </div></a>
        <a href="{% url "main:jeddah_page" %}"><div class="carousel-item">
          <img
            class="carousel-item__img"
            src=" {% static "images/jeddah1.jpg" %} "
            alt="people"
          />
          <div class="carousel-item__details">
            <h5 class="carousel-item__details--title">Jeddah</h5>
          </div>
        </div></a>

        <a href="{% url "main:abha_page" %}"><div class="carousel-item">
          <img
            class="carousel-item__img"
            src=" {% static "images/abhaa.jpg" %} "
            alt="people"
          />
          <div class="carousel-item__details">
            <h5 class="carousel-item__details--title">Abha</h5>
          </div>
        </div></a>
      </div>
    </section>


{% endblock content %}

SaudiArabiaGuide/main/templates/main/weather.html
{% extends "main/base.html" %}
{% block title%} Weather{% endblock  %}

{% block style %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

body {
    color: #fff;
    overflow-x: hidden;
    height: 100%;
    background-repeat: no-repeat;
    background-image: url('/static/images/sa-p1.webp') ;
}

.card {
    background-color: rgba(240, 248, 255, 0);
    background-size: cover;
    width: 600px;
    height: 350px;
    border-radius: 20px;
    box-shadow: 0px 8px 16px 4px #9E9E9E;
    margin-top: 50px;
    margin-bottom: 50px;
}

.time-font {
    font-size: 50px;
}

.sm-font {
    font-size: 18px;
}

.med-font {
    font-size: 28px;
}

.large-font {
    font-size: 60px;
}

{% endblock  %}

{% block content %}
<div class="container-fluid px-1 px-md-4 py-5 mx-auto">
    <div class="row d-flex justify-content-center px-3">
        <div class="card">
            <h2 class="ml-auto mr-4 mt-3 mb-0 text-white">Riyadh</h2>
            <p class="ml-auto mr-4 mb-0 med-font text-white">clear sky</p>
            <h1 class="ml-auto mr-4 large-font text-white">20&#176;</h1>
            <p class="time-font mb-0 ml-4 mt-auto text-white">08:30 <span class="sm-font">AM</span></p>
            <p class="ml-4 mb-4 text-white">Thursday, 14 Mar 2024</p>
        </div>
    </div>
</div>

{% endblock  %}